#!/usr/bin/env bash
# Copyright © 2021 qualIP Software
#
# This file is part of shfuncs:
#
#     https://github.com/qualIP/shfuncs
#
# shfuncs is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 3.0 of the License, or (at your option)
# any later version.
#
# shfuncs is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with shfuncs; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

set -euo pipefail

shfuncs_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
. "$shfuncs_dir/func-test.sh"
. "$shfuncs_dir/func-file.sh"

test_case fix_path_no_slash
test_assert_equal "$(fix_path_no_slash "/some/with space/path")" "/some/with space/path"
test_assert_equal "$(fix_path_no_slash "/some/with space/path/")" "/some/with space/path"
test_assert_equal "$(fix_path_no_slash "/some/path/")" "/some/path"
test_assert_equal "$(fix_path_no_slash "/path/")" "/path"
test_assert_equal "$(fix_path_no_slash "/path")" "/path"
test_assert_equal "$(fix_path_no_slash "/")" "/"

test_case fix_path
test_assert_equal "$(fix_path "/some/with space/path")" "/some/with space/path/"
test_assert_equal "$(fix_path "/some/with space/path/")" "/some/with space/path/"
test_assert_equal "$(fix_path "/some/path/")" "/some/path/"
test_assert_equal "$(fix_path "/path/")" "/path/"
test_assert_equal "$(fix_path "/path")" "/path/"
test_assert_equal "$(fix_path "/")" "/"

test_case find_in_dir
test_assert_equal "$(find_in_dir "$shfuncs_dir" -name "test-file")" "$shfuncs_dir/tests/test-file"
