#!/usr/bin/env bash
# Copyright © 2021 qualIP Software
#
# This file is part of shfuncs:
#
#     https://github.com/qualIP/shfuncs
#
# shfuncs is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 3.0 of the License, or (at your option)
# any later version.
#
# shfuncs is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with shfuncs; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

set -eu

# shellcheck disable=all
SHFUNCS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]:-${(%):-%x}}")/.." && pwd)
. "$SHFUNCS_DIR/func-test.sh"
. "$SHFUNCS_DIR/func-pattern.sh"

has_pipefail && set -o pipefail

test_case is_glob_pattern-1
test_assert_rc 1 is_glob_pattern "abc"

test_case is_glob_pattern-2
test_assert_rc 0 is_glob_pattern "a*bc"

test_case is_glob_pattern-3
test_assert_rc 0 is_glob_pattern "a?bc"

test_case is_glob_pattern-4
test_assert_rc 0 is_glob_pattern "a[b]c"

test_case is_regexp_pattern-1
test_assert_rc 1 is_regexp_pattern "abc"

test_case is_regexp_pattern-2
test_assert_rc 0 is_regexp_pattern "a*bc"

test_case is_regexp_pattern-3
test_assert_rc 0 is_regexp_pattern "^abc"

test_case is_regexp_pattern-4
test_assert_rc 0 is_regexp_pattern "abc$"

test_case expand_glob_pattern-1
test_assert_equal "$(expand_glob_pattern a*)" ''

test_case expand_glob_pattern-2
test_assert_equal "$(expand_glob_pattern a* ba bc)" ''

test_case expand_glob_pattern-3
test_assert_equal "$(expand_glob_pattern a* a1 a2 ba bc)" 'a1 a2'
