#!/usr/bin/env bash
# Copyright © 2021 qualIP Software
#
# This file is part of shfuncs:
#
#     https://github.com/qualIP/shfuncs
#
# shfuncs is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 3.0 of the License, or (at your option)
# any later version.
#
# shfuncs is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with shfuncs; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

set -eu

# shellcheck disable=all
SHFUNCS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]:-${(%):-%x}}")/.." && pwd)
. "$SHFUNCS_DIR/func-test.sh"
. "$SHFUNCS_DIR/func-file.sh"

has_pipefail && set -o pipefail

test_case fix_path_no_slash
test_assert_equal "$(fix_path_no_slash "/some/with space/path")" "/some/with space/path"
test_assert_equal "$(fix_path_no_slash "/some/with space/path/")" "/some/with space/path"
test_assert_equal "$(fix_path_no_slash "/some/path/")" "/some/path"
test_assert_equal "$(fix_path_no_slash "/path/")" "/path"
test_assert_equal "$(fix_path_no_slash "/path")" "/path"
test_assert_equal "$(fix_path_no_slash "/")" "/"

test_case fix_path
test_assert_equal "$(fix_path "/some/with space/path")" "/some/with space/path/"
test_assert_equal "$(fix_path "/some/with space/path/")" "/some/with space/path/"
test_assert_equal "$(fix_path "/some/path/")" "/some/path/"
test_assert_equal "$(fix_path "/path/")" "/path/"
test_assert_equal "$(fix_path "/path")" "/path/"
test_assert_equal "$(fix_path "/")" "/"

test_case find_in_dir
test_assert_equal "$(find_in_dir "$SHFUNCS_DIR" -name "test-file")" "$SHFUNCS_DIR/tests/test-file"

test_case is_temp_file-false
test_assert_rc 1 is_temp_file "$SHFUNCS_DIR/func-file.sh"

test_case is_temp_file-true
test_assert_rc 0 is_temp_file /var/tmp/abc
test_assert_rc 0 is_temp_file /tmp/abc
TMPDIR=$SHFUNCS_DIR test_assert_rc 0 is_temp_file "$SHFUNCS_DIR/func-file.sh"
